version: '3.9'
services:
  dotnet-nginx:
    container_name: dotnet-nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-network
    restart: unless-stopped
  dotnet-api:
    container_name: dotnet-api
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    expose:
      - 5000
    depends_on:
      - dotnet-nginx
    networks:
      - nginx-network
    restart: unless-stopped
  dotnet-certbot:
    image: certbot/certbot
    container_name: dotnet-certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h &
      wait $${!}; done;'"
networks:
  nginx-network:
    driver: bridge